public class BookStorage
{
    public string[] titles = {"Los Gusanos", "Los Troyanos", "El Phishing"};
    public string[] day0 = {"Antes de comenzar debemos entender que es una vulnerabilidad Lo primero que hará un ciberdelincuente, antes de lanzar un ataque, es investigar a su objetivo con el fin de escoger cuál será el mejor vector para hacerle daño. Para hacer esta evaluación, un hacker malicioso requiere la mayor cantidad de datos que pueda adquirir acerca de su objetivo. Por lo tanto, el primer paso para proteger un sistema es reducir al máximo la cantidad de información que un atacante pueda conseguir sobre él.",
                     "Un gusano informático es uno de los programas de malware más antiguos que existen, estos se pueden replicar por si solos, es una subcategoría de un virus y a diferencia de este los gusanos pueden moverse de forma automática sin intervención de un usuario, lo que los hace más peligrosos. Se propagan a otros ordenadores mediante las copias de sí misma, a través de los correos electrónicos, mensajes instantáneos y programas maliciosos de descarga de archivos. Este tipo de malware opera de forma muy silenciosa, pues no es deseable que el usuario detecte la propagación del mismo. Por lo tanto, al ejecutar el virus, el archivo comenzará a verse replicado en directorios, como el disco C o cualquier dispositivo extraíble que se ingrese en el ordenador.",
                     "Las 3 técnicas de ataque: "+System.Environment.NewLine+System.Environment.NewLine+"1.Redes informáticas: alcanzan cualquier equipo conectado a la misma red que el dispositivo que ha sido infectado con gusanos."+System.Environment.NewLine+"2.Ataques phishing: el engaño consiste en hacer que el cibernauta abra un enlace con contenido malicioso, así como la descarga de malware por accidente."+System.Environment.NewLine+"3.Software obsoleto: aprovechan los errores o versiones no optimizadas de un sistema operativo. La desactualización de las apps y cualquier software deja abierta la puerta a malware tan dañino como los gusanos informáticos.",
                     "¿Entonces como nos protegemos?"+System.Environment.NewLine+"Estos malware han evolucionado, entonces es imprescindible tener todo al día, es decir actualizar todos nuestros dispositivos, esto debido a que las empresas están al tanto de estas amenazas y están constantemente sacando actualizaciones para que los usuarios estén protegidos, por tanto lo mínimo que debemos tener actualizado es el sistema operativo, un antivirus, y si es posible, software antimalware, los programas y aplicaciones. Otra cosa importante es nunca abrir archivos adjuntos del e-mail de desconocidos. Además, otra buena práctica es no hacer clic enlaces extraños, utiliza el sentido común y pon el cursor encima a menudo vemos que la URL es sospechosa. También hay que utilizar contraseñas robustas y activar sistemas de autenticación, si es posible."};
    public string[] day1 = {"¿Qué es un troyano?"+System.Environment.NewLine+"El término se tomó prestado de la historia del caballo de madera usado para engañar a los defensores de la cuidad de Troya y poder introducir soldados a hurtadillas. Un troyano oculta software malicioso dentro de un archivo que parece normal. Hay una gran cantidad de virus troyanos en Internet que pueden realizar diversas tareas. La mayoría de los troyanos tienen como objetivo controlar el equipo de un usuario, robar datos e introducir más software malicioso en el equipo de la víctima. Los troyanos no solo afectan a los equipos portátiles y de escritorio. También pueden afectar a los dispositivos móviles.",
                     "Generalmente, los troyanos están adjuntos a un programa que parece legítimo, pero que, en realidad, es una versión falsa de la aplicación cargada con software malicioso. Estos cibercriminales suelen colocar los troyanos en mercados de aplicaciones piratas o no oficiales para que los descarguen los usuarios confiados. Además de las amenazas mencionadas anteriormente, estas aplicaciones también pueden robar información del dispositivo y obtener ganancias enviando mensajes de texto premium.",
                     "¿Cómo funcionan los virus troyanos?"+System.Environment.NewLine+"A diferencia de los virus informáticos, un troyano no puede manifestarse por sí mismo, por lo que necesita que un usuario descargue el lado del servidor de la aplicación para que funcione. Esto significa que se debe implementar el archivo ejecutable y se debe instalar el programa para que el troyano ataque el sistema de un dispositivo. Un virus troyano se propaga a través de correos electrónicos y archivos de aspecto legítimo, adjuntos a correos electrónicos que se envían a tantas bandejas de entrada como sea posible. Cuando se abre el correo electrónico y se descarga el archivo adjunto malicioso, el servidor troyano se instalará y se ejecutará automáticamente cada vez que se encienda el dispositivo infectado.",
                     " Los dispositivos también pueden ser infectados por un troyano a través de tácticas de ingeniería social, que los cibercriminales utilizan para obligar a los usuarios a descargar una aplicación maliciosa. El archivo malicioso podría estar oculto en anuncios publicitarios, anuncios emergentes o enlaces en sitios web. ",
                     "Es necesario aclarar que los troyanos no son virus, sino que son un tipo de malware. En ocasiones, las personas se refieren a ellos como virus troyanos, pero no lo son. Esto se debe a una diferencia fundamental en la forma en que los virus y los troyanos infectan a sus víctimas. Mientras que los virus se autor replican y se propagan de una víctima a otra, los troyanos necesitan que los instale.",
                     "¿Cómo evitar ataques de troyanos?"+System.Environment.NewLine+"1.Descargue aplicaciones y software de fuentes oficiales.Los troyanos suelen alojarse en sitios de descarga de aplicaciones de terceros. Obtenga el software directamente del fabricante o de portales oficiales como la App Store de Apple y Google Play. Aunque también han estado amenazados por troyanos en el pasado, son mucho más seguros que otras opciones."+System.Environment.NewLine+"2.No abra archivos adjuntos de correos electrónicos desconocidos ni haga clic en enlaces extraños. Los correos electrónicos fraudulentos son un vector popular para propagar troyanos. No haga clic en archivos adjuntos ni enlaces de correos electrónicos que no espera recibir. Incluso si el correo electrónico parece legítimo, puede que lo haya falsificado un ciberdelincuente.",
                     "3.Utilice un bloqueador de anuncios o un navegador seguro. Algunos troyanos se propagan a través de anuncios web infectados. Un bloqueador de anuncios o navegador privado evitará que estos y otros anuncios se carguen en el navegador, lo que impedirá que los sitios infectados le proporcionen un troyano."+System.Environment.NewLine+"4.No confíe en el software gratuito.Los creadores de troyanos suelen camuflarlos como juegos gratis y otras aplicaciones que parecen útiles. Si está a punto de instalar algo nuevo, investíguelo primero y lea las opiniones de los usuarios.",
                     "5.No haga clic en anuncios web o enlaces que no conozca.No todas las descargas ocultas se gestionan con anuncios maliciosos. Algunos creadores de malware desarrollan sitios web que pueden instalar automáticamente troyanos y otro malware en los dispositivos en cuanto los visita. Evitar sitios desconocidos reduce el riesgo de descargar un troyano."+System.Environment.NewLine+"6.Utilice una herramienta antivirus.Una herramienta antivirus potente de un proveedor respetable mantendrá a los troyanos lejos de su dispositivo automáticamente. Elija una que funcione como una herramienta de eliminación de malware y que también pueda detectar y eliminar troyanos y otro malware de los dispositivos."};
    public string[] day2 = {"Los ataques de phishing son correos electrónicos, mensajes de texto, llamadas telefónicas o sitios web fraudulentos diseñados  para manipular personas para que descarguen malware, compartan información confidencial como números de la seguridad social y tarjetas de crédito, números de cuentas bancarias, credenciales inicio de sesión, o realicen otras acciones que los exponga a ellos mismos o a sus organizaciones al ciberdelito.",
                     "Los ataques de phishing con éxito a menudo implican la usurpación de identidad, el fraude con tarjeta de crédito, ataques de ransomware, filtraciones de datos y enormes pérdidas financieras para las personas y las corporaciones."+System.Environment.NewLine+"El phishing es la forma más común de ingeniería social, la práctica de engañar, presionar o manipular a las personas para que envíen información o activos a personas indebidas. Los ataques de ingeniería social basan su éxito en tácticas de error humano y presión.",
                     "El atacante normalmente se hace pasar por una persona u organización en la que la víctima confía como por ejemplo, un compañero de trabajo, un jefe, una compañía con la que la víctima o la empresa de la víctima tienen negocios y crea una sensación de urgencia que lleva a la víctima a actuar precipitadamente. Los hackers utilizar estas tácticas porque es más fácil y menos costoso engañar a las personas que atacar un sistema o una red.",
                     "Uno de los ataques más comunes es el de suplantación de identidad que es un ataque de phishing que se dirige a una persona específica, generalmente una persona que tiene acceso privilegiado a datos confidenciales o recursos red, o una autoridad especial que el estafador puede explotar con fines fraudulentos o maliciosos."+System.Environment.NewLine+"Un suplantador de identidad estudia su objetivo para recopilar la información necesaria para hacerse pasar por una persona o entidad en la que el objetivo realmente confía o para hacerse pasar por la persona objetivo. Las redes sociales y los sitios de interacción social, donde las personas felicitan públicamente a sus compañeros de trabajo, apoyan a colegas y proveedores, y tienden a compartir demasiada información sobre reuniones, eventos o planes de viaje, se han convertido en grandes fuentes de información para la investigación de suplantación de identidad.",
                     "Tipos de Phisihing"+System.Environment.NewLine+"El phishing por SMS o smishing es un tipo de phishing que utiliza mensajes de texto de móvil o smartphone. Los esquemas de smishing más efectivos son contextuales, es decir, relacionados con las aplicaciones o la gestión de cuentas de un smartphone. Por ejemplo, los destinatarios pueden recibir un mensaje de texto que les ofrece un regalo de 'agradecimiento' por pagar una factura de teléfono, o pedirles que actualicen la información de su tarjeta de crédito para poder continuar utilizando un servicio de streaming.",
                     "El phishing de voz o vishing es un tipo de phishing que utiliza llamadas telefónicas. Gracias a la tecnología de voz sobre IP (VoIP), los estafadores pueden realizar millones de llamadas de vishing automatizadas al día; a menudo, utilizan la suplantación de ID de llamada entrante para que parezca que sus llamadas se realizan desde organizaciones o números locales legítimos. Las llamadas de vishing generalmente asustan a los destinatarios con advertencias de problemas con el proceso de la tarjeta de crédito, pagos vencidos o problemas con Hacienda. Las personas que responden terminan dando datos confidenciales a personas que trabajan para los estafadores; algunos incluso llegan a darles el control remoto de sus ordenadores a los estafadores al otro lado de la llamada.",
                     "¿Cómo Protegerse?"+System.Environment.NewLine+"Lo mejor que se puede hacer contra estos ataques que buscan el error humano es:Entrenamiento.-  Se anima a las organizaciones a enseñar a los usuarios cómo reconocer las estafas de phishing y a desarrollar mejores prácticas sobre cómo tratar un mensaje de texto o correo electrónico sospechoso. Las organizaciones también pueden fomentar o imponer mejores prácticas que pongan menos presión en los empleados para que sean detectives de phishing. Por ejemplo, las organizaciones pueden establecer y comunicar políticas claras, por ejemplo, un superior o un colega nunca enviará por correo electrónico una solicitud de transferencia de fondos.",
                     " Pueden requerir a los empleados que verifiquen cualquier solicitud de información confidencial poniéndose en contacto con el remitente o visitando directamente el sitio legítimo del remitente, utilizando medios distintos de los proporcionados en el mensaje. Asimismo, pueden insistir en que los empleados informen de los intentos de phishing y los correos electrónicos sospechosos al grupo de TI o seguridad.",
                     "Los consejos que más resaltan son:"+System.Environment.NewLine+"•	Use programas de anti-malware"+System.Environment.NewLine+"•Use firewalls" +System.Environment.NewLine+"•Sospeche de pop-ups y pop-unders"+System.Environment.NewLine+"•Sospeche de los archivos adjuntos en los correos provenientes de fuentes conocidas y desconocidas"+System.Environment.NewLine+"•Sospeche de mensajes de texto y mensajes directos de fuentes conocidas y desconocidas que buscan que haga click en algún link o que pidan información personal"+System.Environment.NewLine+"•No dé su información personal"};
    
}
